# Change these first
owner: luoxthedev # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: SilverHost
    url: https://silverhost.fr
  - name: SilverHost
    url: https://panel.silverhost.fr
  - name: Google
    url: https://google.fr
  - name: dsc.gg
    url: https://dsc.gg/silverhost
  - name: Discord
    url: https://discord.com
  - name: GitHub
    url: https://github.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /status
  logoUrl: https://framerusercontent.com/images/uo19EmNRXxc5YKAllL1pzJvWQw.jpg
  name: Luox Status
  introTitle: "Bienevenue sur la page status de Luox !"
  introMessage: Luox Status est **LA page de status de Luox** (si tu l'avais pas compris mdr)
  navbar:
    - title: Retour à la page status
      href: /status
    - title: Notre GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
